// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lihdopwkldwgzdebbyor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpaGRvcHdrbGR3Z3pkZWJieW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1OTIzNDMsImV4cCI6MjA1NzE2ODM0M30.9DqBeFdT08UnFdaOqPWQalRV1xl5c_QLSKXN-MSjaQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);